@startjson
{
   "light":{
     "effect configuration":{
        "solid red light": {
            "color": "red",
            "brightness": 0.05
        },
        "blinking red light": {
            "color": "red",
            "brightness": 0.05,
            "frequency [HZ]": 2
        }
     },
     "state effects": {
       "work effect": [
        "solid red light",
        "blinking red light",
        "fast blinking red light"
       ],
       "rest effect": ["green solid light"],
       "idle effect": ["IP solid light"]
     },
     "general brightness": 1.0
   },
   "duration": {
     "work" : 25,
     "rest" : 5
   },
   "measurements": {
     "default strategy" : "distanceStrategy",
     "strategy configuration": {
       "distanceStrategy" : {
         "distance [cm]" : 150,
         "observation window [seconds]" : 15
       }
     }
   }
}
@endjson