@startmindmap
<style>
mindmapDiagram {
  ' node {
  '   BackgroundColor lightGreen
  ' }
  ' boxless {
  '   FontColor darkgreen
  ' }
    :depth(1) {
      BackGroundColor lightgreen
    }
    :depth(2) {
      BackGroundColor lightblue
    }
}
</style>

*_ BREAKALERT

++ configuration

+++ restore default configuration

+++ measurements
++++ provide a better measurement sample cleanup\ne.g. wait for 1k samples and delete older than 5min
++++ default strategy
++++ strategy configuration



+++   light
++++  effect configuration

++++  state effects 
+++++ work effect
+++++ rest effect
+++++ idle effect


-- testing

-- command line\nconfiguration
--- --production/debug--
--- measurement strategy

@endmindmap